#include "p18f4550.inc"
OSCCON_CONFIG	EQU	B'10000000'
    
SYSTEM_INITIALIZE CODE
    GLOBAL SYSTEM_INIT
    GLOBAL POR_SYS
    GLOBAL ERROR_SYS
ERROR_SYS:
    GOTO $
POR_SYS:
    ;VERIFICAR REGISTROS POR EN RCON
    RETURN
SYSTEM_INIT:
    BCF	INTCON,GIEH,0;DESACTIVAR ...
    BCF	INTCON,GIEL,0; ... INTERRUPCIONES
    
    BSF	RCON,IPEN,0;ACTIVAR PRIORIDAD DE INTERRUPCIONES
    
    BSF	INTCON,GIEL,0;ACTIVAR LAS INTERRUPCIONES DE BAJA PRIORIDAD
    BSF	INTCON,GIEH,0;ACTIVAR INTERRUPCIONES DE ALTA PRIORIDAD
    RETURN
    END