#include "p18f4550.inc"
; ; ; ; ; ; ; ; ; ; ; ; ;
; TODAS LAS OPERACIONES 
; ; ; ; ; ; ; ; ; ; ; ; ;
T0CON_CONF  EQU	    b'00000111';FOSC/4*256, Clock Instruction Cycle
T0DATA_L    EQU	    0x00
T0DATA_H    EQU	    0x01
T0PRECHARGE EQU	    (0xffff-.46875)

TIMER0_DATA UDATA   0x060
TIMER0_PRECHARGE    RES	2
    
TIMER0_DRIVER CODE
    GLOBAL TIMER0_PRECHARGE
    GLOBAL TIMER0_INIT
    GLOBAL TIMER0_WR
    GLOBAL TIMER0_START
    GLOBAL TIMER0_STOP
TIMER0_INIT:
    MOVLB   0x00
    MOVLW   T0CON_CONF
    MOVWF   T0CON,0
    ; Cargar a RAM la variable de precarga
    MOVLW   ((T0PRECHARGE >> .8)&0xFF)
    MOVWF   TIMER0_PRECHARGE+1,1
    MOVLW   (T0PRECHARGE&0xFF)
    MOVWF   TIMER0_PRECHARGE,1
    CLRF    TMR0L;Vaciar
    CLRF    TMR0H;el timer
    BSF	    INTCON2,TMR0IP,0;ACTIVAR LA PRIORIDAD DE INTERRUPCION ALTA
    BCF	    INTCON,TMR0IF,0;LIMPIAR POSIBLES INTERRUPCIONES
    BSF	    INTCON,TMR0IE,0;ACTIVAR LA INTERRUPCION DEL TIMER
    RETURN
TIMER0_WR:;CARGAR EN 0X00 Y 0X01
    BCF	    T0CON,TMR0ON,0;DETENER EL TIMER0 Y CARGAR LOS DATOS
    MOVF    T0DATA_L,W,0
    MOVWF   TMR0L,0
    MOVF    T0DATA_H,W,0
    MOVWF   TMR0H,0
    RETURN
TIMER0_START:
    BSF	    T0CON,TMR0ON,0
    RETURN
TIMER0_STOP:
    BCF	    T0CON,TMR0ON,0
    RETURN
    END