#include "p18f4550.inc"
; ; ;
;   TRANSMIT STATUS AND CONTROL REG
;	CSRC	- ASYNC MODE. NO CLOCK SOURCE
;	TX9	- SELECT 8 BIT TX
;	TXEN	- TRANSMIT EN
;	SYNC	- ASYNC
;	SENDB	- SYNC BREAK TRANSMIMSSION COMPLETED
;	BRGH	- HIGH SPEED
;	TRMT	- TSR FULL
;	TX9D	- 
; ; ;
UART_TXSTA	EQU	b'00100100'
; ; ;
;   RCSTA RECEIVE STATUS AND CONTROL REG
;	SPEN	- SERIAL PORT EN
;	RX9	- 8 BIT MODE
;	SREN	- ASYNC
;	CREN	- EN RX
;	ADDEN	- ASYNC
;	FERR	- NO FARMING ERROR
;	OERR	- NO OVERRUN ERROR
;	RX9D	- NULL
; ; ;
UART_RCSTA	EQU	b'10010000'
; ; ;
;   BAUDCON BAUD RATE CONTROL REG
;	ABDOVF	- NOT USED
;	RCIDL	- RECEIVE OPERATION IS IDLE
;	RXDTP	- RX IS NOT INVERTED
;	TXCKP	- TX IS NOT INVERTED
;	BRG16	- 8 BIT BAUDRATE GEN
;	NULL
;	WUE	- WAKE-UP EUSART RX INTERRUPT FALLING EDGE
;	ABDEN	- BAUD RATE MEASUREMENT DISABLED
; ; ;
UART_BAUDCON	EQU	b'01000010'
; ; ;
;   SPBRG   BAUD RATE GENERATOR REGISTER WORD
;	SYNC	= 0
;	BRG16	= 0
;	BRGH	= 1
;	BAUDRATE = FOSC / ( 16 ( N+1 ) )
;	    N IS SPBRG VALUE
;	1 = ( BAUD )( 16N+16 ) /( FOSC )
;	( FOSC / ( 16( BAUD ) ) ) - 1 = N
; ; ;
UART_FOSC	EQU	.48000000;Hz
UART_BAUD	EQU	.115200;Baud
UART_SPBRG	EQU	((UART_FOSC/(.16*UART_BAUD))-1) & 0xFF ;.25
UART_PTR_L	EQU	    0x00
UART_PTR_H	EQU	    0x01
	
UART_PTR    UDATA   0x063
UART_PTRL	res	2
UART_COUNTER    res	1
	
UART_CONFIG CODE
    GLOBAL UART_PTRL
    GLOBAL UART_COUNTER
    GLOBAL UART_INIT
    GLOBAL UART_START
    GLOBAL UART_STOP
    GLOBAL UART_MOV
UART_INIT:
    ; Desactivar las interrupciones UART momentaneamente
    BCF	    PIE1,RCIE,0
    BCF	    PIE1,TXIE,0
    ; ;
    ;	CONFIGURAR PINES UART
    ; ;
    BCF	    PORTC,RC7,0
    BCF	    PORTC,RC6,0
    BCF	    LATC,RC7,0
    BCF	    LATC,RC6,0
    BSF	    TRISC,RC7,0
    BSF	    TRISC,RC6,0
    ; ;
    ;	CARGAR LAS CONFIGURACIONES EN LOS REGISTROS
    ; ;
    MOVLW   UART_TXSTA
    MOVWF   TXSTA,0
    MOVLW   UART_RCSTA
    MOVWF   RCSTA,0
    MOVLW   UART_BAUDCON
    MOVWF   BAUDCON,0
    MOVLW   (UART_SPBRG&0xFF)
    MOVWF   SPBRG,0
    
    ; Activar las interrupciones del puerto serial
    BCF	    PIR1,RCIF,0	;LIMPIAR
    BCF	    PIR1,TXIF,0	;   INTERRUPCIONES RX,TX
    ;    BCF	    PIE1,RCIE,0	;DESACTIVAR LAS INTERRUPCIONES RX
    ;    BSF	    PIE1,TXIE,0	;ACTIVAR LAS INTERRUPCIONES TX
    BSF	    IPR1,RCIP,0	;   RX INT AS HIGH LEVEL INT
    BSF	    IPR1,TXIP,0	;   TX INT AS HIGH LEVEL INT
    RETURN
UART_MOV:
    ;CARGAR EL NUEVO PUNTERO AL REGISTRO
    MOVLB   0x00
    MOVF    UART_PTR_L,W,0
    MOVWF   UART_PTRL
    MOVF    UART_PTR_H,W,0
    MOVWF   UART_PTRL+1
    RETURN
UART_START:
    ;BSF	    PIE1,TXIE,0	;ACTIVAR LAS INTERRUPCIONES TX
    BSF	    PIE1,RCIE,0	;ACTIVAR LAS INTERRUPCIONES RX
    BSF	    RCSTA,SPEN,0;ACTIVAR EL PUERTO SERIAL
    RETURN
UART_STOP:
    BCF	    PIE1,TXIE,0	;DESACTIVAR LAS INTERRUPCIONES TX
    BCF	    PIE1,RCIE,0	;DESACTIVAR LAS INTERRUPCIONES RX
    BCF	    RCSTA,SPEN,0;DESACTIVAR EL PUERTO SERIAL
    RETURN
    END